const countryList = {
    USD: "US",
    CAD: "CA",
    GBP: "UK",
    EUR: "EU",
    JPY: "JP",
    CNY: "CN",
    INR: "IN",
    AUD: "AU",
    BRL: "BR",
    RUB: "RU",
    ZAR: "ZA",
    MXN: "MX",
    CHF: "CH",
    KRW: "KR",
    SAR: "SA",
    ARS: "AR",
    TRY: "TR",
    SEK: "SE",
    NOK: "NO",
    DKK: "DK",
    SGD: "SG",
    NZD: "NZ",
    IDR: "ID",
    THB: "TH",
    MYR: "MY",
    VND: "VN",
    PHP: "PH",
    EGP: "EG",
    PKR: "PK",
    BDT: "BD",
    AED: "AE",
    ILS: "IL",
    CLP: "CL",
    COP: "CO",
    PEN: "PE",
    NGN: "NG",
    KES: "KE",
    GHS: "GH",
    UAH: "UA",
    KZT: "KZ"
  };
  

  